In [1]:
import numpy as np
import pandas as pd
# Necessary imports
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os
from datetime import datetime, timedelta
import shutil

df = pd.read_csv("prob_output_stocks_2024.csv")# output from model inference
df["Date"] = pd.to_datetime(df["Date"])
df.sort_values(by=["Date"])

       Unnamed: 0       Date      Prob  Label Symbol
35362       35362 2023-11-29  0.462904      1    IVZ
32708       32708 2023-11-29  0.555739     -1     PG
27261       27261 2023-11-29  0.543904     -1   APTV
48009       48009 2023-11-29  0.583089      1    SYY
15054       15054 2023-11-29  0.671041      1    AEE
...           ...        ...       ...    ...    ...
59311       59311 2024-05-23  0.699339      1    XEL
7749         7749 2024-05-23  0.759419     -1    PWR
41146       41146 2024-05-23  0.445456      1    EXR
29562       29562 2024-05-23  0.254179     -1     BX
28678       28678 2024-05-23  0.365628     -1   AKAM

[60634 rows x 5 columns]

       Unnamed: 0       Date      Prob  Label Symbol
2366         2366 2024-03-28  0.484816      1    EMN
10932       10932 2024-03-28  0.484728     -1    AXP
10941       10941 2024-03-28  0.392360     -1    IRM
18971       18971 2024-03-28  0.463787      1    MET
663           663 2024-03-28  0.531242     -1    SRE
...           ...        ...       ...    ...    ...
5424         5424 2024-05-23  0.556375     -1    CRL
5462         5462 2024-05-23  0.555854      1   EXPD
5509         5509 2024-05-23  0.565640     -1    CME
12322       12322 2024-05-23  0.553600     -1    HSY
0               0 2024-05-23  0.489003      1    KDP

[19920 rows x 5 columns]

In [2]:
# Add in additional features here if needed
def data_generation(data_path, freq):
    if freq == 'D':
        data = pd.read_csv(data_path, index_col=0, parse_dates=True)
    elif freq == 'H':
        data = pd.read_csv(data_path, index_col=0)
        incr = 1e-9
        unix_start = datetime(1970, 1, 1)
        date = []
        for i in range(len(data)):
            date.append(unix_start + timedelta(seconds=incr*data.index[i]))
        data.index = date
        for col in ['open', 'high', 'low', 'close']:
            data[col] = data[col].astype(float) * incr
    # Add features here
    
    data.columns = data.columns.str.lower()
    return data

In [3]:
# Get the list of S&P 500 companies from Wikipedia
sp500_url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
table = pd.read_html(sp500_url)
sp500_df = table[0]
tickers = sp500_df['Symbol'].tolist()
len(tickers)

503

In [4]:
n = 198
exc_tickers = []
inc_tickers = []
error_count = 0
error_list = []
tdf = pd.DataFrame([])
for i, ticker in enumerate(tickers):
    print(f"Working at {ticker, i}")
    try:
        d = data_generation(f'data-SPYstock/{ticker}.csv', freq='D')
        pd_dt = pd.to_datetime(datetime(2023,9,1))
        d = d[(d.index>pd_dt) & (d.index<=datetime(2024,6,17))]
        if len(d)==n:
            inc_tickers.append(ticker)
            d["Symbol"] = ticker
            d["close_d1"] = d["close"].shift(-1)
            d["close_d1_p5"] = d["close_d1"].shift(-5)
            d["true_label"] = np.where(d["close_d1_p5"]>d["close_d1"], 1, -1)
            d.dropna(inplace=True)
            tdf = pd.concat([tdf, d])
        else:
            exc_tickers.append(ticker)
            print(f"Data length mismatch for {ticker}")
    except Exception as e:
        print(f"An error occurred: {e}")
        print(f"Error generating {ticker}")
        error_count += 1
        error_list.append(ticker)

Working at ('MMM', 0)
Working at ('AOS', 1)
Working at ('ABT', 2)
Working at ('ABBV', 3)
Working at ('ACN', 4)
Working at ('ADBE', 5)
Working at ('AMD', 6)
Working at ('AES', 7)
Working at ('AFL', 8)
Working at ('A', 9)
Working at ('APD', 10)
Working at ('ABNB', 11)
Working at ('AKAM', 12)
Working at ('ALB', 13)
Working at ('ARE', 14)
Working at ('ALGN', 15)
Working at ('ALLE', 16)
Working at ('LNT', 17)
Working at ('ALL', 18)
Working at ('GOOGL', 19)
Working at ('GOOG', 20)
Working at ('MO', 21)
Working at ('AMZN', 22)
Working at ('AMCR', 23)
Working at ('AEE', 24)
Working at ('AAL', 25)
Working at ('AEP', 26)
Working at ('AXP', 27)
Working at ('AIG', 28)
Working at ('AMT', 29)
Working at ('AWK', 30)
Working at ('AMP', 31)
Working at ('AME', 32)
Working at ('AMGN', 33)
Working at ('APH', 34)
Working at ('ADI', 35)
Working at ('ANSS', 36)
Working at ('AON', 37)
Working at ('APA', 38)
Working at ('AAPL', 39)
Working at ('AMAT', 40)
Working at ('APTV', 41)
Working at ('ACGL', 42)
Working at ('ADM', 43)
Working at ('ANET', 44)
Working at ('AJG', 45)
Working at ('AIZ', 46)
Working at ('T', 47)
Working at ('ATO', 48)
Working at ('ADSK', 49)
Working at ('ADP', 50)
Working at ('AZO', 51)
Working at ('AVB', 52)
Working at ('AVY', 53)
Working at ('AXON', 54)
Working at ('BKR', 55)
Working at ('BALL', 56)
Working at ('BAC', 57)
Working at ('BK', 58)
Working at ('BBWI', 59)
Working at ('BAX', 60)
Working at ('BDX', 61)
Working at ('BRK.B', 62)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/BRK.B.csv'
Error generating BRK.B
Working at ('BBY', 63)
Working at ('BIO', 64)
Working at ('TECH', 65)
Working at ('BIIB', 66)
Working at ('BLK', 67)
Working at ('BX', 68)
Working at ('BA', 69)
Working at ('BKNG', 70)
Working at ('BWA', 71)
Working at ('BSX', 72)
Working at ('BMY', 73)
Working at ('AVGO', 74)
Working at ('BR', 75)
Working at ('BRO', 76)
Working at ('BF.B', 77)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/BF.B.csv'
Error generating BF.B
Working at ('BLDR', 78)
Working at ('BG', 79)
Working at ('BXP', 80)
Working at ('CDNS', 81)
Working at ('CZR', 82)
Working at ('CPT', 83)
Working at ('CPB', 84)
Working at ('COF', 85)
Working at ('CAH', 86)
Working at ('KMX', 87)
Working at ('CCL', 88)
Working at ('CARR', 89)
Working at ('CTLT', 90)
Working at ('CAT', 91)
Working at ('CBOE', 92)
Working at ('CBRE', 93)
Working at ('CDW', 94)
Working at ('CE', 95)
Working at ('COR', 96)
Working at ('CNC', 97)
Working at ('CNP', 98)
Working at ('CF', 99)
Working at ('CHRW', 100)
Working at ('CRL', 101)
Working at ('SCHW', 102)
Working at ('CHTR', 103)
Working at ('CVX', 104)
Working at ('CMG', 105)
Working at ('CB', 106)
Working at ('CHD', 107)
Working at ('CI', 108)
Working at ('CINF', 109)
Working at ('CTAS', 110)
Working at ('CSCO', 111)
Working at ('C', 112)
Working at ('CFG', 113)
Working at ('CLX', 114)
Working at ('CME', 115)
Working at ('CMS', 116)
Working at ('KO', 117)
Working at ('CTSH', 118)
Working at ('CL', 119)
Working at ('CMCSA', 120)
Working at ('CAG', 121)
Working at ('COP', 122)
Working at ('ED', 123)
Working at ('STZ', 124)
Working at ('CEG', 125)
Working at ('COO', 126)
Working at ('CPRT', 127)
Working at ('GLW', 128)
Working at ('CPAY', 129)
Working at ('CTVA', 130)
Working at ('CSGP', 131)
Working at ('COST', 132)
Working at ('CTRA', 133)
Working at ('CRWD', 134)
Working at ('CCI', 135)
Working at ('CSX', 136)
Working at ('CMI', 137)
Working at ('CVS', 138)
Working at ('DHR', 139)
Working at ('DRI', 140)
Working at ('DVA', 141)
Working at ('DAY', 142)
Working at ('DECK', 143)
Working at ('DE', 144)
Working at ('DAL', 145)
Working at ('DVN', 146)
Working at ('DXCM', 147)
Working at ('FANG', 148)
Working at ('DLR', 149)
Working at ('DFS', 150)
Working at ('DG', 151)
Working at ('DLTR', 152)
Working at ('D', 153)
Working at ('DPZ', 154)
Working at ('DOV', 155)
Working at ('DOW', 156)
Working at ('DHI', 157)
Working at ('DTE', 158)
Working at ('DUK', 159)
Working at ('DD', 160)
Working at ('EMN', 161)
Working at ('ETN', 162)
Working at ('EBAY', 163)
Working at ('ECL', 164)
Working at ('EIX', 165)
Working at ('EW', 166)
Working at ('EA', 167)
Working at ('ELV', 168)
Working at ('EMR', 169)
Working at ('ENPH', 170)
Working at ('ETR', 171)
Working at ('EOG', 172)
Working at ('EPAM', 173)
Working at ('EQT', 174)
Working at ('EFX', 175)
Working at ('EQIX', 176)
Working at ('EQR', 177)
Working at ('ESS', 178)
Working at ('EL', 179)
Working at ('ETSY', 180)
Working at ('EG', 181)
Working at ('EVRG', 182)
Working at ('ES', 183)
Working at ('EXC', 184)
Working at ('EXPE', 185)
Working at ('EXPD', 186)
Working at ('EXR', 187)
Working at ('XOM', 188)
Working at ('FFIV', 189)
Working at ('FDS', 190)
Working at ('FICO', 191)
Working at ('FAST', 192)
Working at ('FRT', 193)
Working at ('FDX', 194)
Working at ('FIS', 195)
Working at ('FITB', 196)
Working at ('FSLR', 197)
Working at ('FE', 198)
Working at ('FI', 199)
Working at ('FMC', 200)
Working at ('F', 201)
Working at ('FTNT', 202)
Working at ('FTV', 203)
Working at ('FOXA', 204)
Working at ('FOX', 205)
Working at ('BEN', 206)
Working at ('FCX', 207)
Working at ('GRMN', 208)
Working at ('IT', 209)
Working at ('GE', 210)
Working at ('GEHC', 211)
Working at ('GEV', 212)
Data length mismatch for GEV
Working at ('GEN', 213)
Working at ('GNRC', 214)
Working at ('GD', 215)
Working at ('GIS', 216)
Working at ('GM', 217)
Working at ('GPC', 218)
Working at ('GILD', 219)
Working at ('GPN', 220)
Working at ('GL', 221)
Working at ('GDDY', 222)
Working at ('GS', 223)
Working at ('HAL', 224)
Working at ('HIG', 225)
Working at ('HAS', 226)
Working at ('HCA', 227)
Working at ('DOC', 228)
Working at ('HSIC', 229)
Working at ('HSY', 230)
Working at ('HES', 231)
Working at ('HPE', 232)
Working at ('HLT', 233)
Working at ('HOLX', 234)
Working at ('HD', 235)
Working at ('HON', 236)
Working at ('HRL', 237)
Working at ('HST', 238)
Working at ('HWM', 239)
Working at ('HPQ', 240)
Working at ('HUBB', 241)
Working at ('HUM', 242)
Working at ('HBAN', 243)
Working at ('HII', 244)
Working at ('IBM', 245)
Working at ('IEX', 246)
Working at ('IDXX', 247)
Working at ('ITW', 248)
Working at ('INCY', 249)
Working at ('IR', 250)
Working at ('PODD', 251)
Working at ('INTC', 252)
Working at ('ICE', 253)
Working at ('IFF', 254)
Working at ('IP', 255)
Working at ('IPG', 256)
Working at ('INTU', 257)
Working at ('ISRG', 258)
Working at ('IVZ', 259)
Working at ('INVH', 260)
Working at ('IQV', 261)
Working at ('IRM', 262)
Working at ('JBHT', 263)
Working at ('JBL', 264)
Working at ('JKHY', 265)
Working at ('J', 266)
Working at ('JNJ', 267)
Working at ('JCI', 268)
Working at ('JPM', 269)
Working at ('JNPR', 270)
Working at ('K', 271)
Working at ('KVUE', 272)
Working at ('KDP', 273)
Working at ('KEY', 274)
Working at ('KEYS', 275)
Working at ('KMB', 276)
Working at ('KIM', 277)
Working at ('KMI', 278)
Working at ('KKR', 279)
Working at ('KLAC', 280)
Working at ('KHC', 281)
Working at ('KR', 282)
Working at ('LHX', 283)
Working at ('LH', 284)
Working at ('LRCX', 285)
Working at ('LW', 286)
Working at ('LVS', 287)
Working at ('LDOS', 288)
Working at ('LEN', 289)
Working at ('LLY', 290)
Working at ('LIN', 291)
Working at ('LYV', 292)
Working at ('LKQ', 293)
Working at ('LMT', 294)
Working at ('L', 295)
Working at ('LOW', 296)
Working at ('LULU', 297)
Working at ('LYB', 298)
Working at ('MTB', 299)
Working at ('MRO', 300)
Working at ('MPC', 301)
Working at ('MKTX', 302)
Working at ('MAR', 303)
Working at ('MMC', 304)
Working at ('MLM', 305)
Working at ('MAS', 306)
Working at ('MA', 307)
Working at ('MTCH', 308)
Working at ('MKC', 309)
Working at ('MCD', 310)
Working at ('MCK', 311)
Working at ('MDT', 312)
Working at ('MRK', 313)
Working at ('META', 314)
Working at ('MET', 315)
Working at ('MTD', 316)
Working at ('MGM', 317)
Working at ('MCHP', 318)
Working at ('MU', 319)
Working at ('MSFT', 320)
Working at ('MAA', 321)
Working at ('MRNA', 322)
Working at ('MHK', 323)
Working at ('MOH', 324)
Working at ('TAP', 325)
Working at ('MDLZ', 326)
Working at ('MPWR', 327)
Working at ('MNST', 328)
Working at ('MCO', 329)
Working at ('MS', 330)
Working at ('MOS', 331)
Working at ('MSI', 332)
Working at ('MSCI', 333)
Working at ('NDAQ', 334)
Working at ('NTAP', 335)
Working at ('NFLX', 336)
Working at ('NEM', 337)
Working at ('NWSA', 338)
Working at ('NWS', 339)
Working at ('NEE', 340)
Working at ('NKE', 341)
Working at ('NI', 342)
Working at ('NDSN', 343)
Working at ('NSC', 344)
Working at ('NTRS', 345)
Working at ('NOC', 346)
Working at ('NCLH', 347)
Working at ('NRG', 348)
Working at ('NUE', 349)
Working at ('NVDA', 350)
Working at ('NVR', 351)
Working at ('NXPI', 352)
Working at ('ORLY', 353)
Working at ('OXY', 354)
Working at ('ODFL', 355)
Working at ('OMC', 356)
Working at ('ON', 357)
Working at ('OKE', 358)
Working at ('ORCL', 359)
Working at ('OTIS', 360)
Working at ('PCAR', 361)
Working at ('PKG', 362)
Working at ('PANW', 363)
Working at ('PARA', 364)
Working at ('PH', 365)
Working at ('PAYX', 366)
Working at ('PAYC', 367)
Working at ('PYPL', 368)
Working at ('PNR', 369)
Working at ('PEP', 370)
Working at ('PFE', 371)
Working at ('PCG', 372)
Working at ('PM', 373)
Working at ('PSX', 374)
Working at ('PNW', 375)
Working at ('PNC', 376)
Working at ('POOL', 377)
Working at ('PPG', 378)
Working at ('PPL', 379)
Working at ('PFG', 380)
Working at ('PG', 381)
Working at ('PGR', 382)
Working at ('PLD', 383)
Working at ('PRU', 384)
Working at ('PEG', 385)
Working at ('PTC', 386)
Working at ('PSA', 387)
Working at ('PHM', 388)
Working at ('QRVO', 389)
Working at ('PWR', 390)
Working at ('QCOM', 391)
Working at ('DGX', 392)
Working at ('RL', 393)
Working at ('RJF', 394)
Working at ('RTX', 395)
Working at ('O', 396)
Working at ('REG', 397)
Working at ('REGN', 398)
Working at ('RF', 399)
Working at ('RSG', 400)
Working at ('RMD', 401)
Working at ('RVTY', 402)
Working at ('ROK', 403)
Working at ('ROL', 404)
Working at ('ROP', 405)
Working at ('ROST', 406)
Working at ('RCL', 407)
Working at ('SPGI', 408)
Working at ('CRM', 409)
Working at ('SBAC', 410)
Working at ('SLB', 411)
Working at ('STX', 412)
Working at ('SRE', 413)
Working at ('NOW', 414)
Working at ('SHW', 415)
Working at ('SPG', 416)
Working at ('SWKS', 417)
Working at ('SJM', 418)
Working at ('SW', 419)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/SW.csv'
Error generating SW
Working at ('SNA', 420)
Working at ('SOLV', 421)
Data length mismatch for SOLV
Working at ('SO', 422)
Working at ('LUV', 423)
Working at ('SWK', 424)
Working at ('SBUX', 425)
Working at ('STT', 426)
Working at ('STLD', 427)
Working at ('STE', 428)
Working at ('SYK', 429)
Working at ('SMCI', 430)
Working at ('SYF', 431)
Working at ('SNPS', 432)
Working at ('SYY', 433)
Working at ('TMUS', 434)
Working at ('TROW', 435)
Working at ('TTWO', 436)
Working at ('TPR', 437)
Working at ('TRGP', 438)
Working at ('TGT', 439)
Working at ('TEL', 440)
Working at ('TDY', 441)
Working at ('TFX', 442)
Working at ('TER', 443)
Working at ('TSLA', 444)
Working at ('TXN', 445)
Working at ('TXT', 446)
Working at ('TMO', 447)
Working at ('TJX', 448)
Working at ('TSCO', 449)
Working at ('TT', 450)
Working at ('TDG', 451)
Working at ('TRV', 452)
Working at ('TRMB', 453)
Working at ('TFC', 454)
Working at ('TYL', 455)
Working at ('TSN', 456)
Working at ('USB', 457)
Working at ('UBER', 458)
Working at ('UDR', 459)
Working at ('ULTA', 460)
Working at ('UNP', 461)
Working at ('UAL', 462)
Working at ('UPS', 463)
Working at ('URI', 464)
Working at ('UNH', 465)
Working at ('UHS', 466)
Working at ('VLO', 467)
Working at ('VTR', 468)
Working at ('VLTO', 469)
Data length mismatch for VLTO
Working at ('VRSN', 470)
Working at ('VRSK', 471)
Working at ('VZ', 472)
Working at ('VRTX', 473)
Working at ('VTRS', 474)
Working at ('VICI', 475)
Working at ('V', 476)
Working at ('VST', 477)
Working at ('VMC', 478)
Working at ('WRB', 479)
Working at ('GWW', 480)
Working at ('WAB', 481)
Working at ('WBA', 482)
Working at ('WMT', 483)
Working at ('DIS', 484)
Working at ('WBD', 485)
Working at ('WM', 486)
Working at ('WAT', 487)
Working at ('WEC', 488)
Working at ('WFC', 489)
Working at ('WELL', 490)
Working at ('WST', 491)
Working at ('WDC', 492)
Working at ('WY', 493)
Working at ('WMB', 494)
Working at ('WTW', 495)
Working at ('WYNN', 496)
Working at ('XEL', 497)
Working at ('XYL', 498)
Working at ('YUM', 499)
Working at ('ZBRA', 500)
Working at ('ZBH', 501)
Working at ('ZTS', 502)

In [5]:
tdf.to_csv("./true_labels_stocks_2024.csv")

#tdf

In [6]:
tdf

,open,high,low,close,adj close,volume,Symbol,close_d1,close_d1_p5,true_label
Date,,,,,,,,,,
2023-09-05,89.297661,90.518394,88.946487,89.339462,85.921562,5817583,MMM,88.938126,84.489967,-1
2023-09-06,89.063545,89.306023,88.076920,88.938126,85.535576,3210423,MMM,88.586960,85.551842,-1
2023-09-07,88.779266,89.289299,87.759193,88.586960,85.197853,3476652,MMM,88.829430,84.498329,-1
2023-09-08,88.695648,88.954849,88.143814,88.829430,85.431046,3317824,MMM,90.209030,84.481606,-1
2023-09-11,89.464882,90.484947,89.289299,90.209030,86.757858,3398314,MMM,89.598663,83.804352,-1
...,...,...,...,...,...,...,...,...,...,...
2024-06-03,170.039993,174.270004,169.979996,172.369995,172.369995,2142700,ZTS,171.880005,178.539993,1
2024-06-04,170.929993,172.259995,169.660004,171.880005,171.880005,1304400,ZTS,175.820007,175.850006,1
2024-06-05,172.899994,176.729996,172.899994,175.820007,175.820007,1870800,ZTS,176.779999,171.320007,-1
2024-06-06,174.520004,176.899994,173.990005,176.779999,176.779999,2722200,ZTS,176.919998,170.550003,-1
2024-06-07,175.899994,177.119995,175.250000,176.919998,176.919998,1819400,ZTS,178.830002,170.899994,-1

In [8]:
tdf["Symbol"].value_counts()

Symbol
MMM     192
MS      192
NDSN    192
NI      192
NKE     192
       ...
EBAY    192
ETN     192
EMN     192
DD      192
ZTS     192
Name: count, Length: 497, dtype: int64

In [12]:
#historic data

n = 250
exc_tickers = []
inc_tickers = []
error_count = 0
error_list = []
tdf = pd.DataFrame([])
for i, ticker in enumerate(tickers):
    print(f"Working at {ticker, i}")
    try:
        d = data_generation(f'data-SPYstock/{ticker}.csv', freq='D')
        pd_dt = pd.to_datetime(datetime(2023,1,1))
        d = d[(d.index>pd_dt) & (d.index<=datetime(2023,12,31))]
        # print(len(d))
        if len(d)==n:
            inc_tickers.append(ticker)
            d["Symbol"] = ticker
            d["close_d1"] = d["close"].shift(-1)
            d["close_d1_p5"] = d["close_d1"].shift(-5)
            d["return_d5"] = (d["close_d1_p5"] - d["close_d1"] )/d["close_d1"] 
            d.dropna(inplace=True)
            tdf = pd.concat([tdf, d])
        else:
            exc_tickers.append(ticker)
            print(f"Data length mismatch for {ticker}")
    except Exception as e:
        print(f"An error occurred: {e}")
        print(f"Error generating {ticker}")
        error_count += 1
        error_list.append(ticker)

Working at ('MMM', 0)
Working at ('AOS', 1)
Working at ('ABT', 2)
Working at ('ABBV', 3)
Working at ('ACN', 4)
Working at ('ADBE', 5)
Working at ('AMD', 6)
Working at ('AES', 7)
Working at ('AFL', 8)
Working at ('A', 9)
Working at ('APD', 10)
Working at ('ABNB', 11)
Working at ('AKAM', 12)
Working at ('ALB', 13)
Working at ('ARE', 14)
Working at ('ALGN', 15)
Working at ('ALLE', 16)
Working at ('LNT', 17)
Working at ('ALL', 18)
Working at ('GOOGL', 19)
Working at ('GOOG', 20)
Working at ('MO', 21)
Working at ('AMZN', 22)
Working at ('AMCR', 23)
Working at ('AEE', 24)
Working at ('AAL', 25)
Working at ('AEP', 26)
Working at ('AXP', 27)
Working at ('AIG', 28)
Working at ('AMT', 29)
Working at ('AWK', 30)
Working at ('AMP', 31)
Working at ('AME', 32)
Working at ('AMGN', 33)
Working at ('APH', 34)
Working at ('ADI', 35)
Working at ('ANSS', 36)
Working at ('AON', 37)
Working at ('APA', 38)
Working at ('AAPL', 39)
Working at ('AMAT', 40)
Working at ('APTV', 41)
Working at ('ACGL', 42)
Working at ('ADM', 43)
Working at ('ANET', 44)
Working at ('AJG', 45)
Working at ('AIZ', 46)
Working at ('T', 47)
Working at ('ATO', 48)
Working at ('ADSK', 49)
Working at ('ADP', 50)
Working at ('AZO', 51)
Working at ('AVB', 52)
Working at ('AVY', 53)
Working at ('AXON', 54)
Working at ('BKR', 55)
Working at ('BALL', 56)
Working at ('BAC', 57)
Working at ('BK', 58)
Working at ('BBWI', 59)
Working at ('BAX', 60)
Working at ('BDX', 61)
Working at ('BRK.B', 62)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/BRK.B.csv'
Error generating BRK.B
Working at ('BBY', 63)
Working at ('BIO', 64)
Working at ('TECH', 65)
Working at ('BIIB', 66)
Working at ('BLK', 67)
Working at ('BX', 68)
Working at ('BA', 69)
Working at ('BKNG', 70)
Working at ('BWA', 71)
Working at ('BSX', 72)
Working at ('BMY', 73)
Working at ('AVGO', 74)
Working at ('BR', 75)
Working at ('BRO', 76)
Working at ('BF.B', 77)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/BF.B.csv'
Error generating BF.B
Working at ('BLDR', 78)
Working at ('BG', 79)
Working at ('BXP', 80)
Working at ('CDNS', 81)
Working at ('CZR', 82)
Working at ('CPT', 83)
Working at ('CPB', 84)
Working at ('COF', 85)
Working at ('CAH', 86)
Working at ('KMX', 87)
Working at ('CCL', 88)
Working at ('CARR', 89)
Working at ('CTLT', 90)
Working at ('CAT', 91)
Working at ('CBOE', 92)
Working at ('CBRE', 93)
Working at ('CDW', 94)
Working at ('CE', 95)
Working at ('COR', 96)
Working at ('CNC', 97)
Working at ('CNP', 98)
Working at ('CF', 99)
Working at ('CHRW', 100)
Working at ('CRL', 101)
Working at ('SCHW', 102)
Working at ('CHTR', 103)
Working at ('CVX', 104)
Working at ('CMG', 105)
Working at ('CB', 106)
Working at ('CHD', 107)
Working at ('CI', 108)
Working at ('CINF', 109)
Working at ('CTAS', 110)
Working at ('CSCO', 111)
Working at ('C', 112)
Working at ('CFG', 113)
Working at ('CLX', 114)
Working at ('CME', 115)
Working at ('CMS', 116)
Working at ('KO', 117)
Working at ('CTSH', 118)
Working at ('CL', 119)
Working at ('CMCSA', 120)
Working at ('CAG', 121)
Working at ('COP', 122)
Working at ('ED', 123)
Working at ('STZ', 124)
Working at ('CEG', 125)
Working at ('COO', 126)
Working at ('CPRT', 127)
Working at ('GLW', 128)
Working at ('CPAY', 129)
Working at ('CTVA', 130)
Working at ('CSGP', 131)
Working at ('COST', 132)
Working at ('CTRA', 133)
Working at ('CRWD', 134)
Working at ('CCI', 135)
Working at ('CSX', 136)
Working at ('CMI', 137)
Working at ('CVS', 138)
Working at ('DHR', 139)
Working at ('DRI', 140)
Working at ('DVA', 141)
Working at ('DAY', 142)
Working at ('DECK', 143)
Working at ('DE', 144)
Working at ('DAL', 145)
Working at ('DVN', 146)
Working at ('DXCM', 147)
Working at ('FANG', 148)
Working at ('DLR', 149)
Working at ('DFS', 150)
Working at ('DG', 151)
Working at ('DLTR', 152)
Working at ('D', 153)
Working at ('DPZ', 154)
Working at ('DOV', 155)
Working at ('DOW', 156)
Working at ('DHI', 157)
Working at ('DTE', 158)
Working at ('DUK', 159)
Working at ('DD', 160)
Working at ('EMN', 161)
Working at ('ETN', 162)
Working at ('EBAY', 163)
Working at ('ECL', 164)
Working at ('EIX', 165)
Working at ('EW', 166)
Working at ('EA', 167)
Working at ('ELV', 168)
Working at ('EMR', 169)
Working at ('ENPH', 170)
Working at ('ETR', 171)
Working at ('EOG', 172)
Working at ('EPAM', 173)
Working at ('EQT', 174)
Working at ('EFX', 175)
Working at ('EQIX', 176)
Working at ('EQR', 177)
Working at ('ESS', 178)
Working at ('EL', 179)
Working at ('ETSY', 180)
Working at ('EG', 181)
Working at ('EVRG', 182)
Working at ('ES', 183)
Working at ('EXC', 184)
Working at ('EXPE', 185)
Working at ('EXPD', 186)
Working at ('EXR', 187)
Working at ('XOM', 188)
Working at ('FFIV', 189)
Working at ('FDS', 190)
Working at ('FICO', 191)
Working at ('FAST', 192)
Working at ('FRT', 193)
Working at ('FDX', 194)
Working at ('FIS', 195)
Working at ('FITB', 196)
Working at ('FSLR', 197)
Working at ('FE', 198)
Working at ('FI', 199)
Working at ('FMC', 200)
Working at ('F', 201)
Working at ('FTNT', 202)
Working at ('FTV', 203)
Working at ('FOXA', 204)
Working at ('FOX', 205)
Working at ('BEN', 206)
Working at ('FCX', 207)
Working at ('GRMN', 208)
Working at ('IT', 209)
Working at ('GE', 210)
Working at ('GEHC', 211)
Working at ('GEV', 212)
Data length mismatch for GEV
Working at ('GEN', 213)
Working at ('GNRC', 214)
Working at ('GD', 215)
Working at ('GIS', 216)
Working at ('GM', 217)
Working at ('GPC', 218)
Working at ('GILD', 219)
Working at ('GPN', 220)
Working at ('GL', 221)
Working at ('GDDY', 222)
Working at ('GS', 223)
Working at ('HAL', 224)
Working at ('HIG', 225)
Working at ('HAS', 226)
Working at ('HCA', 227)
Working at ('DOC', 228)
Working at ('HSIC', 229)
Working at ('HSY', 230)
Working at ('HES', 231)
Working at ('HPE', 232)
Working at ('HLT', 233)
Working at ('HOLX', 234)
Working at ('HD', 235)
Working at ('HON', 236)
Working at ('HRL', 237)
Working at ('HST', 238)
Working at ('HWM', 239)
Working at ('HPQ', 240)
Working at ('HUBB', 241)
Working at ('HUM', 242)
Working at ('HBAN', 243)
Working at ('HII', 244)
Working at ('IBM', 245)
Working at ('IEX', 246)
Working at ('IDXX', 247)
Working at ('ITW', 248)
Working at ('INCY', 249)
Working at ('IR', 250)
Working at ('PODD', 251)
Working at ('INTC', 252)
Working at ('ICE', 253)
Working at ('IFF', 254)
Working at ('IP', 255)
Working at ('IPG', 256)
Working at ('INTU', 257)
Working at ('ISRG', 258)
Working at ('IVZ', 259)
Working at ('INVH', 260)
Working at ('IQV', 261)
Working at ('IRM', 262)
Working at ('JBHT', 263)
Working at ('JBL', 264)
Working at ('JKHY', 265)
Working at ('J', 266)
Working at ('JNJ', 267)
Working at ('JCI', 268)
Working at ('JPM', 269)
Working at ('JNPR', 270)
Working at ('K', 271)
Working at ('KVUE', 272)
Data length mismatch for KVUE
Working at ('KDP', 273)
Working at ('KEY', 274)
Working at ('KEYS', 275)
Working at ('KMB', 276)
Working at ('KIM', 277)
Working at ('KMI', 278)
Working at ('KKR', 279)
Working at ('KLAC', 280)
Working at ('KHC', 281)
Working at ('KR', 282)
Working at ('LHX', 283)
Working at ('LH', 284)
Working at ('LRCX', 285)
Working at ('LW', 286)
Working at ('LVS', 287)
Working at ('LDOS', 288)
Working at ('LEN', 289)
Working at ('LLY', 290)
Working at ('LIN', 291)
Working at ('LYV', 292)
Working at ('LKQ', 293)
Working at ('LMT', 294)
Working at ('L', 295)
Working at ('LOW', 296)
Working at ('LULU', 297)
Working at ('LYB', 298)
Working at ('MTB', 299)
Working at ('MRO', 300)
Working at ('MPC', 301)
Working at ('MKTX', 302)
Working at ('MAR', 303)
Working at ('MMC', 304)
Working at ('MLM', 305)
Working at ('MAS', 306)
Working at ('MA', 307)
Working at ('MTCH', 308)
Working at ('MKC', 309)
Working at ('MCD', 310)
Working at ('MCK', 311)
Working at ('MDT', 312)
Working at ('MRK', 313)
Working at ('META', 314)
Working at ('MET', 315)
Working at ('MTD', 316)
Working at ('MGM', 317)
Working at ('MCHP', 318)
Working at ('MU', 319)
Working at ('MSFT', 320)
Working at ('MAA', 321)
Working at ('MRNA', 322)
Working at ('MHK', 323)
Working at ('MOH', 324)
Working at ('TAP', 325)
Working at ('MDLZ', 326)
Working at ('MPWR', 327)
Working at ('MNST', 328)
Working at ('MCO', 329)
Working at ('MS', 330)
Working at ('MOS', 331)
Working at ('MSI', 332)
Working at ('MSCI', 333)
Working at ('NDAQ', 334)
Working at ('NTAP', 335)
Working at ('NFLX', 336)
Working at ('NEM', 337)
Working at ('NWSA', 338)
Working at ('NWS', 339)
Working at ('NEE', 340)
Working at ('NKE', 341)
Working at ('NI', 342)
Working at ('NDSN', 343)
Working at ('NSC', 344)
Working at ('NTRS', 345)
Working at ('NOC', 346)
Working at ('NCLH', 347)
Working at ('NRG', 348)
Working at ('NUE', 349)
Working at ('NVDA', 350)
Working at ('NVR', 351)
Working at ('NXPI', 352)
Working at ('ORLY', 353)
Working at ('OXY', 354)
Working at ('ODFL', 355)
Working at ('OMC', 356)
Working at ('ON', 357)
Working at ('OKE', 358)
Working at ('ORCL', 359)
Working at ('OTIS', 360)
Working at ('PCAR', 361)
Working at ('PKG', 362)
Working at ('PANW', 363)
Working at ('PARA', 364)
Working at ('PH', 365)
Working at ('PAYX', 366)
Working at ('PAYC', 367)
Working at ('PYPL', 368)
Working at ('PNR', 369)
Working at ('PEP', 370)
Working at ('PFE', 371)
Working at ('PCG', 372)
Working at ('PM', 373)
Working at ('PSX', 374)
Working at ('PNW', 375)
Working at ('PNC', 376)
Working at ('POOL', 377)
Working at ('PPG', 378)
Working at ('PPL', 379)
Working at ('PFG', 380)
Working at ('PG', 381)
Working at ('PGR', 382)
Working at ('PLD', 383)
Working at ('PRU', 384)
Working at ('PEG', 385)
Working at ('PTC', 386)
Working at ('PSA', 387)
Working at ('PHM', 388)
Working at ('QRVO', 389)
Working at ('PWR', 390)
Working at ('QCOM', 391)
Working at ('DGX', 392)
Working at ('RL', 393)
Working at ('RJF', 394)
Working at ('RTX', 395)
Working at ('O', 396)
Working at ('REG', 397)
Working at ('REGN', 398)
Working at ('RF', 399)
Working at ('RSG', 400)
Working at ('RMD', 401)
Working at ('RVTY', 402)
Working at ('ROK', 403)
Working at ('ROL', 404)
Working at ('ROP', 405)
Working at ('ROST', 406)
Working at ('RCL', 407)
Working at ('SPGI', 408)
Working at ('CRM', 409)
Working at ('SBAC', 410)
Working at ('SLB', 411)
Working at ('STX', 412)
Working at ('SRE', 413)
Working at ('NOW', 414)
Working at ('SHW', 415)
Working at ('SPG', 416)
Working at ('SWKS', 417)
Working at ('SJM', 418)
Working at ('SW', 419)
An error occurred: [Errno 2] No such file or directory: 'data-SPYstock/SW.csv'
Error generating SW
Working at ('SNA', 420)
Working at ('SOLV', 421)
Data length mismatch for SOLV
Working at ('SO', 422)
Working at ('LUV', 423)
Working at ('SWK', 424)
Working at ('SBUX', 425)
Working at ('STT', 426)
Working at ('STLD', 427)
Working at ('STE', 428)
Working at ('SYK', 429)
Working at ('SMCI', 430)
Working at ('SYF', 431)
Working at ('SNPS', 432)
Working at ('SYY', 433)
Working at ('TMUS', 434)
Working at ('TROW', 435)
Working at ('TTWO', 436)
Working at ('TPR', 437)
Working at ('TRGP', 438)
Working at ('TGT', 439)
Working at ('TEL', 440)
Working at ('TDY', 441)
Working at ('TFX', 442)
Working at ('TER', 443)
Working at ('TSLA', 444)
Working at ('TXN', 445)
Working at ('TXT', 446)
Working at ('TMO', 447)
Working at ('TJX', 448)
Working at ('TSCO', 449)
Working at ('TT', 450)
Working at ('TDG', 451)
Working at ('TRV', 452)
Working at ('TRMB', 453)
Working at ('TFC', 454)
Working at ('TYL', 455)
Working at ('TSN', 456)
Working at ('USB', 457)
Working at ('UBER', 458)
Working at ('UDR', 459)
Working at ('ULTA', 460)
Working at ('UNP', 461)
Working at ('UAL', 462)
Working at ('UPS', 463)
Working at ('URI', 464)
Working at ('UNH', 465)
Working at ('UHS', 466)
Working at ('VLO', 467)
Working at ('VTR', 468)
Working at ('VLTO', 469)
Data length mismatch for VLTO
Working at ('VRSN', 470)
Working at ('VRSK', 471)
Working at ('VZ', 472)
Working at ('VRTX', 473)
Working at ('VTRS', 474)
Working at ('VICI', 475)
Working at ('V', 476)
Working at ('VST', 477)
Working at ('VMC', 478)
Working at ('WRB', 479)
Working at ('GWW', 480)
Working at ('WAB', 481)
Working at ('WBA', 482)
Working at ('WMT', 483)
Working at ('DIS', 484)
Working at ('WBD', 485)
Working at ('WM', 486)
Working at ('WAT', 487)
Working at ('WEC', 488)
Working at ('WFC', 489)
Working at ('WELL', 490)
Working at ('WST', 491)
Working at ('WDC', 492)
Working at ('WY', 493)
Working at ('WMB', 494)
Working at ('WTW', 495)
Working at ('WYNN', 496)
Working at ('XEL', 497)
Working at ('XYL', 498)
Working at ('YUM', 499)
Working at ('ZBRA', 500)
Working at ('ZBH', 501)
Working at ('ZTS', 502)

In [13]:
tdf.to_csv("./historic_data_stocks.csv")

tdf

,open,high,low,close,adj close,volume,Symbol,close_d1,close_d1_p5,return_d5
Date,,,,,,,,,,
2023-01-03,101.605354,102.541809,100.643814,102.399666,94.329193,3124909,MMM,104.640465,107.959869,0.031722
2023-01-04,103.135452,104.757523,102.600334,104.640465,96.393394,3312561,MMM,102.809364,108.152176,0.051968
2023-01-05,103.854515,104.155518,102.391304,102.809364,94.706612,3117494,MMM,105.953178,108.285950,0.022017
2023-01-06,104.230766,106.295990,103.469902,105.953178,97.602646,2890732,MMM,106.011703,105.852844,-0.001499
2023-01-09,106.187294,108.244148,105.443146,106.011703,97.656563,3434075,MMM,107.132111,102.633781,-0.041989
...,...,...,...,...,...,...,...,...,...,...
2023-12-14,198.000000,201.919998,198.000000,200.089996,199.069595,3044400,ZTS,196.289993,194.979996,-0.006674
2023-12-15,199.410004,199.410004,193.970001,196.289993,195.288971,4058300,ZTS,196.720001,195.500000,-0.006202
2023-12-18,197.809998,198.139999,195.600006,196.720001,195.716797,1543100,ZTS,198.080002,196.899994,-0.005957
2023-12-19,197.779999,198.979996,197.240005,198.080002,197.069855,1600300,ZTS,194.630005,197.160004,0.012999
2023-12-20,198.000000,199.339996,194.570007,194.630005,193.637436,1833200,ZTS,194.660004,197.369995,0.013922